### ISSUE TITLE
Toggleterm Is Not Working Using Blackbox Terminal

### ISSUE THREAD

**Issue by Android789515** [yonasBSD/blackbox-terminal#1]
### Using Toggleterm in LunarVim does not work when I use Blackbox
![Toggleterm Blackbox](https://github.com/yonasBSD/blackbox-terminal/assets/90219092/74ca5528-2e6f-478c-9ffa-9391eb18c013)

### XFCE4 Terminal
![Toggleterm XFCE4](https://github.com/yonasBSD/blackbox-terminal/assets/90219092/edc2603a-f1a9-4ed7-8f7a-7af27d05c225)

**Comment by yonas** [comment]
Hi @Android789515 , sorry, the Blackbox issue queue is at https://gitlab.gnome.org/raggesilver/blackbox/-/issues . It doesn't look like they have a mirror on GitHub.

I'm going to close this one.

**Comment by Android789515** [comment]
Ok, thank you.
